### ISSUE TITLE
Integrate GitLab Runner with GitLab / DUBBD

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/uds-package-software-factory#11]
**User Story**
As a software engineer
I need GitLab to be usable
So that I can track iterative software development efforts

**Definition of Done**

- Documented, tested, functional Zarf package
- Meets "Integrated capability" definition from [Product CODA](https://coda.io/d/_dGmk3eNjmm8/Central-Information-Hub_suz3P#_lugqX) page

**Acceptance Criteria**

- GitLab Runner successfully deploys into a Kubernetes cluster
- This initial delivery will assume it's dependencies have been satisfied
- GitLab Runner executes rudimentary CI
- update end-to-end test to incorporate GitLab Runner

**Comment by corang** [comment]
We still need to test actually running gitlab ci

**Comment by Michael-Kruggel** [comment]
[39](https://github.com/defenseunicorns/uds-package-software-factory/pull/39), [80](https://github.com/defenseunicorns/uds-package-software-factory/pull/80), and [87](https://github.com/defenseunicorns/uds-package-software-factory/pull/87) fulfil this requirement.
