### ISSUE TITLE
Constrain swf package to only deploy to valid versions/flavors of dubbd

### ISSUE THREAD

**Issue by corang** [defenseunicorns/uds-package-software-factory#5]
As a user of the software factory package
I want to easily understand if the cluster I am deploying to will accept the package
So that I don't have to suffer when dependencies aren't met

**Acceptance Criteria**
* User is informed before deployment begins

**Comment by corang** [comment]
probably gonna need a capability that checks the dubbd zarf secret - will also double as a place to write a verbose error about dubbd needing to be deployed before software factory

**Comment by mikevanhemert** [comment]
Could this be accomplished with a Zarf change? Add a `dependsOn` thing?
