### ISSUE TITLE
Output templateFile as Zarf config

### ISSUE THREAD

**Issue by justin-o12** [defenseunicorns/uds-package-software-factory#66]
References:
- https://spacelift.io/blog/terraform-templates
- https://developer.hashicorp.com/terraform/language/functions/templatefile

**Comment by zachariahmiller** [comment]
This changed to uds-config.yaml (bundle config) and is implemented in uds-swf-aws repo. In the main.tf under the /terraform directory.

https://github.com/defenseunicorns/uds-swf-aws/pull/10
