### ISSUE TITLE
Configurable GitLab S3 Bucket Names

### ISSUE THREAD

**Issue by justin-o12** [defenseunicorns/uds-package-software-factory#81]
S3 bucket names need to be unique within a partition across all AWS accounts and regions.  We will need a way to use unique names for the [GitLab buckets](https://github.com/defenseunicorns/uds-package-software-factory/blob/main/README.md?plain=1#L61).

We can use the original bucket names as a root in combination with another string.  We need to decide if we want to use:
- Just a prefix
- Just a suffix
- Both prefix and suffix
- Operator's choice (prefix and suffix are optional)

**Comment by corang** [comment]
Going with suffix via variable
